'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from './ui/card';
import { Input } from './ui/input';
import { Button } from './ui/button';
import { Spinner } from './ui/spinner';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { AVAILABLE_MODELS } from '@/lib/ai-config';

interface Summary {
  title: string;
  summary: string;
  transcriptPreview: string;
  provider?: string;
  modelUsed?: string;
  videoUrl?: string;
}

interface VideoSummarizerProps {
  onSubmit: (url: string, model: string) => Promise<Summary | null>;
}

export function VideoSummarizer({ onSubmit }: VideoSummarizerProps) {
  const [url, setUrl] = useState('');
  const [model, setModel] = useState(AVAILABLE_MODELS.length > 0 ? AVAILABLE_MODELS[0].id : 'openai/gpt-4o-mini');
  const [isLoading, setIsLoading] = useState(false);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (AVAILABLE_MODELS.length > 0 && !AVAILABLE_MODELS.find(m => m.id === model)) {
      setModel(AVAILABLE_MODELS[0].id);
    }
  }, [model]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setSummary(null);

    try {
      const result = await onSubmit(url, model);
      setSummary(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred while fetching the summary.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle>YouTube Video Summarizer</CardTitle>
        <CardDescription>Enter a YouTube video URL to get an AI-generated summary, formatted for direct use in news articles.</CardDescription>
      </CardHeader>
      <CardContent>
        <form id="videosummarizer-form" onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Input
              type="url"
              placeholder="Enter YouTube URL (e.g., https://www.youtube.com/watch?v=...)"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              required
              aria-label="YouTube Video URL"
            />
          </div>
          <div className="space-y-2">
            <Select value={model} onValueChange={setModel} disabled={AVAILABLE_MODELS.length === 0}>
              <SelectTrigger aria-label="Select AI Model">
                <SelectValue placeholder={AVAILABLE_MODELS.length > 0 ? "Select a model" : "No models available"} />
              </SelectTrigger>
              <SelectContent>
                {AVAILABLE_MODELS.length > 0 ? (
                  AVAILABLE_MODELS.map((selectableModel) => (
                    <SelectItem key={selectableModel.id} value={selectableModel.id}>
                      {selectableModel.name} 
                    </SelectItem>
                  ))
                ) : (
                  <SelectItem value="none" disabled>No models configured</SelectItem>
                )}
              </SelectContent>
            </Select>
          </div>
        </form>
      </CardContent>
      <CardFooter>
        <Button 
          type="submit"
          form="videosummarizer-form"
          disabled={isLoading || !url || AVAILABLE_MODELS.length === 0}
          className="w-full"
        >
          {isLoading ? (
            <>
              <Spinner className="mr-2" />
              Generating Summary...
            </>
          ) : (
            'Generate Summary'
          )}
        </Button>
      </CardFooter>

      {error && (
        <Card className="mt-4 p-4 border-destructive bg-destructive/10">
          <CardHeader>
            <CardTitle className="text-destructive">Error</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-destructive-foreground">{error}</p>
          </CardContent>
        </Card>
      )}

      {summary && (
        <Card className="mt-4 p-6 space-y-4">
          <CardHeader>
            <CardTitle>{summary.title || 'Summary'}</CardTitle>
            {(summary.provider || summary.modelUsed) && (
                <CardDescription className="text-sm text-muted-foreground">
                  Generated by {summary.provider || 'N/A'} using {summary.modelUsed || 'N/A'}.
                  {summary.videoUrl && (
                    <> <a href={summary.videoUrl} target="_blank" rel="noopener noreferrer" className="underline hover:text-primary">Watch Video</a></>
                  )}
                </CardDescription>
              )}
          </CardHeader>
          <CardContent className="space-y-4 prose prose-sm dark:prose-invert max-w-none">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {summary.summary}
            </ReactMarkdown>
            
            {summary.transcriptPreview && (
              <div className="mt-6 pt-4 border-t">
                <h3 className="text-base font-semibold mb-1 text-muted-foreground">Transcript Preview:</h3>
                <p className="text-xs text-muted-foreground whitespace-pre-wrap bg-muted p-2 rounded">
                  {summary.transcriptPreview}
                </p>
              </div>
            )}
          </CardContent>
          <CardFooter className="flex-col sm:flex-row gap-2">
            <Button
              onClick={() => {
                if (summary?.summary) {
                  navigator.clipboard.writeText(summary.summary);
                }
              }}
              variant="outline"
              size="sm"
              className="w-full"
            >
              Copy Summary (Markdown)
            </Button>
            {summary.videoUrl && (
               <Button asChild variant="secondary" size="sm" className="w-full">
                 <a href={summary.videoUrl} target="_blank" rel="noopener noreferrer">
                    Watch Original Video
                 </a>
               </Button>
            )}
          </CardFooter>
        </Card>
      )}
    </Card>
  );
} 